name: PlaceholderAPI
main: me.clip.placeholderapi.PlaceholderAPIPlugin
version: 2.2.0
author: [extended_clip]
description: Clips public placeholder API that allows other plugins to obtain and register placeholders to show information from other plugins!
permissions:
    placeholderapi.*:
        description: ability to use all commands
        children:
            placeholderapi.admin: true
    placeholderapi.admin:
        description: ability to use all commands
        children:
            placeholderapi.list: true
            placeholderapi.reload: true
            placeholderapi.parse: true
            placeholderapi.injector.chat.bypass: true
            placeholderapi.injector.signs.bypass: true
            placeholderapi.injector.anvil.bypass: true
    placeholderapi.list:
        description: ability to use the list command
        default: op
    placeholderapi.reload:
        description: ability to use the reload command
        default: op
    placeholderapi.parse:
        description: ability to use parse command
        default: op
    placeholderapi.injector.chat.bypass:
        description: ability to use placeholders in chat messages
        default: op
    placeholderapi.injector.signs.bypass:
        description: ability to use placeholders in signs
        default: op
    placeholderapi.injector.anvil.bypass:
        description: ability to use placeholders in anvils
        default: op
commands:
   placeholderapi:
     description: PlaceholderAPI command
     aliases: [clipsplaceholderapi, papi]
     